openapi: 3.0.3
info:
  title: BeCat Crowdsourced Translation Annotation Platform
  description: |-
    Burmese is inherently a low resource language with very little high quality available for Machine Learning Experts to use to train their ML models on. We want to change that by allowing average Myanmar people to contribute to the data generation process so that a better future can be built
    
    This is the public facing API that would be consumed by the frontend interfaces.
  version: 1.0.0
  contact:
    email: contact@datamyanmar.org
servers:
  - url: http://localhost:8080/api
  - url: http://becat.datamyanmar.org/api
tags:
  - name: user
    description: individual related stuff
  - name: language-pair
    description: getting and setting language pairs
  - name: global
    description: publicly available data
paths:
  /user/login:
    post:
      operationId: loginUser
      tags:
        - user
      summary: Login
      description: Authenticates the user with user-id and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                loginid:
                  type: string
                password:
                  type: string
              required:
                - loginid
                - password
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /user/logout:
    post:
      operationId: logoutUser
      summary: Logout
      tags:
        - user
      description: Logs out the user, invalidating the session token.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful logout
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /user/history:
    get:
      operationId: getUserHistory
      summary: Get Annotation History
      description: Fetches the annotation history of the logged-in user.
      tags:
        - user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of annotations made by the user
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_annotations:
                    type: integer
                  annotated_today:
                    type: integer
                  history:
                    type: object
                    items:
                      type: object
                      properties:
                        language_pair_id:
                          type: integer
                        annotation:
                          $ref: '#/components/schemas/AnnotationType'
                        feedback:
                          type: string
                        timestamp:
                          type: string

  /language-pair/retrieve:
    get:
      operationId: getLanguagePair
      summary: Get a random language pair
      tags:
        - language-pair
      description: Fetch a random language pair that is decided to be needed to annotate by the system
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of language pairs
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  burmese:
                    type: string
                  english:
                    type: string

  /language-pair/annotate:
    put:
      operationId: annotateLanguagePair
      summary: Annotate
      tags:
        - language-pair
      description: Annotates a particular language pair with "OK" or "NOT OK" and additional feedback.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                language_pair_id:
                  type: string
                annotation:
                  $ref: '#/components/schemas/AnnotationType'
                feedback:
                  type: string
              required:
                - language_pair_id
                - annotation
      responses:
        '201':
          description: Annotation submitted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /global-stats:
    get:
      operationId: getGlobalStats
      summary: Get Global Statistics
      description: Displays global statistics like total annotations, total users, etc.
      security:
        - bearerAuth: []
      tags:
        - global
      responses:
        '200':
          description: Global statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_users:
                    type: integer
                  total_text:
                    type: integer
                  total_annotated_data:
                    type: integer
                  total_unannotated_data:
                    type: integer

components:
  schemas:
    AnnotationType:
      type: string
      enum: [UNMARKED, OKAY, MAYBE, REJECTED]
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
